In [ ]:
# Dump Path: r'/content/drive/My Drive/BE Project/Content Dataset Prediction Dumps/'
# Dataset Path
# r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv'

In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import glob
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Load the dataset
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')
df.head()
df.describe()

Status      Currency  ...  Risks and Challenges Words           FAQ
count  18065.000000  18065.000000  ...                18065.000000  18065.000000
mean       0.497924      1.337448  ...                  129.775588      0.677830
std        0.500010      0.773829  ...                   97.240961      2.046338
min        0.000000      1.000000  ...                    0.000000      0.000000
25%        0.000000      1.000000  ...                   68.000000      0.000000
50%        0.000000      1.000000  ...                  105.000000      0.000000
75%        1.000000      1.000000  ...                  163.000000      0.000000
max        1.000000      6.000000  ...                 1888.000000     47.000000

[8 rows x 21 columns]

In [ ]:
df.shape

(18065, 21)

### Pledged Amount Prediction

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 19 columns]

In [ ]:
y=df['Pledged']
y.head()

0       6
1     180
2    1941
3     130
4    1015
Name: Pledged, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression(normalize=True).fit(X_train, y_train)
reg.score(X,y)

0.46810917474178726

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 10127.150641655793
Mean Squared Error: 2233757633.7944255
Root Mean Squared Error: 47262.64522637751


In [ ]:
c = pd.DataFrame(reg.coef_,X_test.columns, columns=['Coeff'])
c

Coeff
Currency                      77.014372
Main Category                349.267453
Sub Category                  -0.220199
Rewards                      424.600819
Goal                           0.000237
Backers                       91.174915
Duration                     120.624320
Facebook Connected          1964.062160
Facebook Friends              -1.131366
Facebook Shares                1.924288
Has Video                  -1813.411687
Has Website                -1367.473510
Projects Created            -145.990307
Projects Backed              -85.464971
Videos                     -2140.833724
Images                      -531.193462
Description Words             -0.374937
Risks and Challenges Words    15.231647
FAQ                         3680.261002

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(reg, X, y, cv=10)
scores

array([ 0.09451138, -0.49815342,  0.52249534,  0.5759755 ,  0.37948453,
        0.61347396,  0.39637079, -0.03532798,  0.60050116,  0.40999247])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.3059323728810313
Max Accuracy 0.6134739607343229


Descision Tree

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 19 columns]

In [ ]:
y=df['Pledged']
y.head()

0       6
1     180
2    1941
3     130
4    1015
Name: Pledged, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)
dtr.score(X_test,y_test)

-1.6868218630521152

In [ ]:
y_pred = dtr.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 7468.343173431735
Mean Squared Error: 7968726209.571218
Root Mean Squared Error: 89267.7221036317


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dtr, X, y, cv=8)
scores

array([ 0.36240271,  0.26901645,  0.61487842,  0.70469064,  0.10561179,
        0.35291758,  0.69941291, -0.94002006])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.2711138053596609
Max Accuracy 0.7046906412110259


Random Forest

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 19 columns]

In [ ]:
y=df['Pledged']
y.head()

0       6
1     180
2    1941
3     130
4    1015
Name: Pledged, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 42)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
regressor.score(X_test,y_test)

0.07562643438533201

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5305.325187638376
Mean Squared Error: 2741558702.1392074
Root Mean Squared Error: 52359.89593323508


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor, X, y, cv=10)
scores

array([-0.62745345, -0.25297032,  0.49054673,  0.48942935,  0.56699947,
        0.60705716,  0.53833481,  0.71253842,  0.65572793,  0.12685222])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.33070623189266524
Max Accuracy 0.7125384209922996


### Number of Backers Prediction

Linear Regression

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged','Backers'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 18 columns]

In [ ]:
y=df['Backers']
y.head()

0     2
1     5
2    62
3     5
4    16
Name: Backers, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_test, y_test)

0.30583006552444136

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 137.08955741946644
Mean Squared Error: 310956.08004344365
Root Mean Squared Error: 557.6343605297683


In [ ]:
c = pd.DataFrame(reg.coef_,X_test.columns, columns=['Coeff'])
c

Coeff
Currency                   -24.383861
Main Category               -2.345688
Sub Category                 0.001216
Rewards                     -1.573052
Goal                         0.000003
Duration                    -0.859820
Facebook Connected         -63.962610
Facebook Friends             0.013678
Facebook Shares              0.113693
Has Video                   -2.528583
Has Website                 12.264870
Projects Created             4.587236
Projects Backed              0.706833
Videos                       9.274078
Images                       8.844292
Description Words            0.036406
Risks and Challenges Words   0.074166
FAQ                         74.111995

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(reg, X, y, cv=10)
scores

array([0.50236006, 0.19576606, 0.3689424 , 0.4546628 , 0.4906977 ,
       0.3694578 , 0.38585151, 0.15770253, 0.40795398, 0.08980373])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.342319857376713
Max Accuracy 0.502360058433474


Decision Tree

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged','Backers'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 18 columns]

In [ ]:
y=df['Backers']
y.head()

0     2
1     5
2    62
3     5
4    16
Name: Backers, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,y_train)
dtr.score(X,y)

0.7245394371203867

In [ ]:
y_pred = dtr.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 140.08671586715866
Mean Squared Error: 370209.86863468634
Root Mean Squared Error: 608.4487395292116


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dtr, X, y, cv=10)
scores

array([ 0.14549758,  0.2492869 ,  0.179829  ,  0.12515781,  0.04887853,
       -1.38236227, -1.82559182,  0.0125631 ,  0.07513347, -2.31462127])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy -0.46862289621560616
Max Accuracy 0.24928690427959765


Random Forest

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/9.Content Dataset (Final)/Content Dataset Cleaned Final.csv')

In [ ]:
X = df.drop(['Status','Pledged','Backers'], axis=1)
X.head()

Currency  Main Category  ...  Risks and Challenges Words  FAQ
0         1              6  ...                         153    0
1         1              1  ...                          98    0
2         1              8  ...                          66    2
3         1              3  ...                         169    0
4         1              3  ...                         216    0

[5 rows x 18 columns]

In [ ]:
y=df['Backers']
y.head()

0     2
1     5
2    62
3     5
4    16
Name: Backers, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 42)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
regressor.score(X_test,y_test)

0.43713879566902425

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 101.99235399753996
Mean Squared Error: 252135.83160947822
Root Mean Squared Error: 502.131289215757


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor, X, y, cv=10)
scores

array([0.47397784, 0.37861302, 0.52781227, 0.07558614, 0.72458254,
       0.10120095, 0.47328601, 0.72074335, 0.57057213, 0.07795926])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.4124333524403221
Max Accuracy 0.7245825415859135
