In [ ]:
# Dump Path: r'/content/drive/My Drive/BE Project/General Dataset Prediction Dumps/'
# Final Datasets Path
# 1. r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv'
# 2. r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 2.csv'

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import glob
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Dataset Overview
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')
df.head()

name  ... state
0                   Ardmore Junction: A Feature Film  ...     1
1        Support producing 3 Peace Day events in NYC  ...     1
2  Mojobot - World's first tangible coding robot ...  ...     1
3  The World's Best Passport Case for Two | futar...  ...     1
4  The Little Girl, The Ocean, and The Moon: A Ch...  ...     1

[5 rows x 17 columns]

### **Pledged Amount (USD) Prediction**

Linear Regression

In [ ]:
# Load the dataset
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd', 'state'], axis=1)
X.head()

country  currency  ...  description_score  description_prediction
0        1         1  ...           1.554951                       1
1        1         1  ...          -0.143421                       1
2       10         6  ...           0.232367                       1
3       20        14  ...           0.909679                       1
4        1         1  ...           9.094467                       1

[5 rows x 10 columns]

In [ ]:
y = df['pledged_amount_usd']
y.head()

0    23509
1     2249
2    19370
3     2196
4    26156
Name: pledged_amount_usd, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression(normalize=True).fit(X_train, y_train)
reg.score(X,y)

0.6339320387545058

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 9392.017601702453
Mean Squared Error: 4391132067.877974
Root Mean Squared Error: 66265.61753939952


In [ ]:
c = pd.DataFrame(reg.coef_,X_test.columns, columns=['Coeff'])
c

Coeff
country                  309.959129
currency                -634.428133
main_category           -162.706721
sub_category              -0.033733
time_before_launch         0.848339
funding_time             139.839469
goal_amount_usd            0.000209
no_of_backers             87.192132
description_score       -211.022824
description_prediction  1534.293241

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(reg, X, y, cv=10)
scores

array([0.69867643, 0.53131492, 0.64361915, 0.63017453, 0.71233639,
       0.51786905, 0.54576794, 0.72928468, 0.617427  , 0.64516128])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.6271631360630072
Max Accuracy 0.7292846817431445


Descision Tree

In [ ]:
# Load the dataset
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd', 'state'], axis=1)
X.head()

country  currency  ...  description_score  description_prediction
0        1         1  ...           1.554951                       1
1        1         1  ...          -0.143421                       1
2       10         6  ...           0.232367                       1
3       20        14  ...           0.909679                       1
4        1         1  ...           9.094467                       1

[5 rows x 10 columns]

In [ ]:
y = df['pledged_amount_usd']
y.head()

0    23509
1     2249
2    19370
3     2196
4    26156
Name: pledged_amount_usd, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,y_train)
dtr.score(X_test,y_test)

0.5158336947641199

In [ ]:
y_pred = dtr.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 8303.787475088813
Mean Squared Error: 7190398598.200524
Root Mean Squared Error: 84796.21806543335


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dtr, X, y, cv=10)
scores

array([ 0.46575834,  0.32840662, -0.23073114,  0.56735502,  0.33284624,
        0.44085021,  0.13174782,  0.4620773 ,  0.28228069,  0.58702778])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.3367618879148817
Max Accuracy 0.5870277818436489


Random Forest

In [ ]:
# Load the dataset
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd', 'state'], axis=1)
X.head()

country  currency  ...  description_score  description_prediction
0        1         1  ...           1.554951                       1
1        1         1  ...          -0.143421                       1
2       10         6  ...           0.232367                       1
3       20        14  ...           0.909679                       1
4        1         1  ...           9.094467                       1

[5 rows x 10 columns]

In [ ]:
y = df['pledged_amount_usd']
y.head()

0    23509
1     2249
2    19370
3     2196
4    26156
Name: pledged_amount_usd, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df.head(10)

Actual  Predicted
61435      293    3869.83
118963    3230    3892.44
113808   20007   17570.52
77272     1780    1695.92
16361     3082    9214.52
28624     3071    3386.79
122940    7594    7019.44
30073       26      71.09
59862      817    1977.01
43363      476    2258.69

In [ ]:
regressor.score(X_test,y_test)

0.719426272882449

In [ ]:
import pickle
with open(r'/content/drive/My Drive/BE Project/General Dataset Classification Dumps/Final Prediction Pledged Model','wb') as f:
  pickle.dump(regressor,f)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 6375.231059498022
Mean Squared Error: 4233701185.670443
Root Mean Squared Error: 65066.89777198881


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor, X, y, cv=10)
scores

array([0.73451624, 0.55991404, 0.57926986, 0.62119215, 0.66892541,
       0.54892346, 0.63824723, 0.6976563 , 0.70093855, 0.68919447])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.6438777689450279
Max Accuracy 0.734516237929546


### **Number of Backers Prediction**

Linear Regression

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd','no_of_backers', 'state'], axis=1)
X.head()

country  currency  ...  description_score  description_prediction
0        1         1  ...           1.554951                       1
1        1         1  ...          -0.143421                       1
2       10         6  ...           0.232367                       1
3       20        14  ...           0.909679                       1
4        1         1  ...           9.094467                       1

[5 rows x 9 columns]

In [ ]:
y = df['no_of_backers']
y.head()

0    256
1      8
2     59
3      6
4    463
Name: no_of_backers, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_test, y_test)

0.00833440716260414

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 199.6385651421483
Mean Squared Error: 1254788.2123836272
Root Mean Squared Error: 1120.1732956929598


In [ ]:
c = pd.DataFrame(reg.coef_,X_test.columns, columns=['Coeff'])
c

Coeff
country                   3.633794
currency                 -6.735452
main_category             3.846299
sub_category             -0.000654
time_before_launch        0.180399
funding_time              1.447851
goal_amount_usd           0.000009
description_score        -3.032923
description_prediction  196.807985

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(reg, X, y, cv=10)
scores

array([0.00501593, 0.0084213 , 0.01314887, 0.00925807, 0.01303088,
       0.01669335, 0.01520224, 0.0090329 , 0.00731506, 0.00946117])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy 0.010657976560429439
Max Accuracy 0.01669334536825573


Descision Tree

In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd','no_of_backers', 'state'], axis=1)
X.head()

country  currency  ...  description_score  description_prediction
0        1         1  ...           1.554951                       1
1        1         1  ...          -0.143421                       1
2       10         6  ...           0.232367                       1
3       20        14  ...           0.909679                       1
4        1         1  ...           9.094467                       1

[5 rows x 9 columns]

In [ ]:
y = df['no_of_backers']
y.head()

0    256
1      8
2     59
3      6
4    463
Name: no_of_backers, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,y_train)
dtr.score(X,y)

0.45865550918626496

In [ ]:
y_pred = dtr.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 194.45612381942638
Mean Squared Error: 1862601.6758025733
Root Mean Squared Error: 1364.7716570190682


In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dtr, X, y, cv=10)
scores

array([-0.23016395, -0.0687479 , -2.65956374, -0.57999287, -0.5308493 ,
       -1.52769064, -0.70755762, -0.78666071, -0.46255095, -0.69350031])

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")

Cross Validated Average Accuracy -0.824727799235083
Max Accuracy -0.06874789629322886


Random Forest

In [ ]:
# Load the dataset
df = pd.read_csv(r'/content/drive/My Drive/Predictive Analysis of Crowdfunding Platforms/7.General Dataset (Final)/General Dataset Cleaned Final 1.csv')

In [ ]:
X = df.drop(['name','description', 'state_change_time', 'goal_amount', 'pledged_amount','pledged_amount_usd','no_of_backers', 'state'], axis=1)
X.head()

In [ ]:
y = df['no_of_backers']
y.head()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 42)
regressor.fit(X_train, y_train)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df.head(50)

In [ ]:
regressor.score(X_test,y_test)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(regressor, X, y, cv=10)
scores

In [ ]:
from statistics import mean
print(f"Cross Validated Average Accuracy {mean(scores)}")
print(f"Max Accuracy {max(scores)}")